Accept array of secrets, not just one
octokit/webhooks.js pull request #777
Opened 2022-12-06 02:32 UTC by nwf-msr

Resolves #770.

----

## Behavior

### Before the change?

* Only one secret could be specified for a WebHook object.

### After the change?

* A bare secret or an array of secrets are each accepted.  In the latter case, any match will be accepted.

----

## Additional info

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

- [x] No

### Pull request type

I do not seem to be able to add labels, but please add `Type: Feature` for me?

----

2022-12-06 03:00 UTC, gr2m requested changes
PR looks great so far! Can you please also update the `### Constructor` options table?

Also can you run `npm run lint:fix` to make the prettier linter happy?

2022-12-06 17:33 UTC, gr2m commented
can you look into the failing tests?

Please don't force-push changes, we don't mind a messy commit history in pull requests, we squash & merge them in the end anyway

2022-12-08 00:46 UTC, nwf-msr commented
What'd I do to make CodeQL unhappy? :(

2022-12-08 00:58 UTC, wolfy1339 commented
It's not you, it's CodeQL being uncooperative.

Just ignore it

2022-12-14 01:47 UTC, gr2m reviewed
I think the pull request looks good as is.

Good point about the `.sign()` method. Given that the first secret in a given array of secrets has special meaning, I wonder if it would make more sense to keep the secret as is, but add an additional option such as `alternativeSecrets` or maybe some other name that better conveys that these secrets are used for incoming request verification only? 

My understanding is that in your case, there will always only be one other secret. Do you see a use case where more than two secrets would be needed to be provided?

2022-12-14 01:47 UTC, gr2m commented on README.md
> +always be made with the first secret.
```suggestion
then update your Webhook receiver to accept only the new secret. New signatures will
be calculated using the first secret.
```

2022-12-14 01:47 UTC, gr2m commented on README.md
> +        <em>(String or String Array)</em>
```suggestion
        <em>(String or Array of Strings)</em>
```

2022-12-14 01:47 UTC, gr2m commented on README.md
> +        with the first secret.
```suggestion
        Secret as configured in GitHub Settings.  If set to an array of strings, a
        webhook request will be accepted if its signature verifies
        with any of the given secrets. New signatures will always be
        calculated using the first secret.
```

2022-12-16 15:57 UTC, nwf-msr commented
> I think the pull request looks good as is.
> 
> Good point about the `.sign()` method. Given that the first secret in a given array of secrets has special meaning, I wonder if it would make more sense to keep the secret as is, but add an additional option such as `alternativeSecrets` or maybe some other name that better conveys that these secrets are used for incoming request verification only?

That makes sense.  I'll take a stab at that approach.

> My understanding is that in your case, there will always only be one other secret. Do you see a use case where more than two secrets would be needed to be provided?

That's true and no, I don't see reason to need more than one active and one retiring secret, at least, at the moment.  I'm tempted to leave `alternativeSecrets` as an array of strings, tho', just in case.  It's not like it's hard or on the hot path most of the time.

2023-01-10 01:16 UTC, gr2m commented
maybe call them `alternativeSecretsForVerification` to make clear they won't be used for the `.sign()` method?

2023-02-06 18:07 UTC, nwf-msr commented
Belatedly, I've raised https://github.com/octokit/webhooks.js/pull/811 .

2023-02-10 01:48 UTC, wolfy1339 commented
Instead of opening a separate PR, you could have simply reused this one.

Closing in favour of #811

2023-02-10 01:48 UTC, closed without merging

2023-02-10 01:50 UTC, nwf-msr commented
I didn't reuse this one because I was advised not to force-push changes and enough time had elapsed that doing the work on a new checkout seemed wise.

2023-02-10 01:54 UTC, wolfy1339 commented
When you need to update using a rebase, a force-push can be warranted.
When you simply always squash your changes, it can become harder to review changes since the last time it was reviewed, and we don't mind having many commits.